version: '3'
services:
  client:
    build: ./client
    ports:
    - "3000:3000"
  api:
    build: ./api
    ports:
    - "9000:9000"
    depends_on:
    - mongo
  mongo:
    image: mongo
    ports:
    - "27017:27017"
